name: test
on:
  push:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
  pull_request:
    paths-ignore:
      - LICENSE
      - README.*
      - examples
jobs:
  nim:
    name: nim tests
    uses: nimbase/setup-nim-action/.github/workflows/test_clue.yml@main
    with:
      nim-version: '2.2.x'